# Generated by Django 5.1.1 on 2024-09-05 12:14

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(
                null=True,
                upload_to=user.models.profile_image_path,
                verbose_name="image",
            ),
        ),
    ]
